### ISSUE TITLE
Launcher is not deployed during 2nd start of oc

### ISSUE THREAD

**Issue by cmoulliard** [openshift-istio/origin#1]
## Install istio + launcher (1st time)

```
wget -O istiooc https://github.com/openshift-istio/origin/releases/download/istio-3.9-0.7.1-alpha4/istiooc_linux
chmod +x istiooc
export PATH=$(pwd):$PATH
mv istiooc oc
oc
oc version
oc cluster up --istio   --public-hostname=192.168.99.50   --launcher   --launcher-openshift-user=admin   --launcher-openshift-password=admin   --launcher-openshift-username=cmoulliard   --launcher-openshift-token=MYTOKEN
oc login -u system:admin
oc adm policy add-cluster-role-to-user cluster-admin admin
oc login -u admin -p admin
```

Result = OK as devex openshift project is created and route to access the front end is created

BUT 

## Stop and restart oc

```
oc cluster down
oc cluster up --istio   --public-hostname=192.168.99.50   --launcher   --launcher-openshift-user=admin   --launcher-openshift-password=admin   --launcher-openshift-username=cmoulliard   --launcher-openshift-token=MYTOKEN
oc login -u system:admin
oc adm policy add-cluster-role-to-user cluster-admin admin
oc login -u admin -p admin

oc projects
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
    istio-system
    kube-public
    kube-system
  * myproject - My Project
    openshift
    openshift-infra
    openshift-node
    openshift-web-console

Using project "myproject" on server "https://192.168.99.50:8443".
```

Result = NOK as no devex project created and launcher installed !!!

**Comment by knrc** [comment]
Strange, this works when I try this locally

<pre>rincewind:origin kevin$ istiooc cluster up --istio --launcher
rincewind:origin kevin$ istiooc login -u developer
rincewind:origin kevin$ istiooc get pods --all-namespaces
NAMESPACE               NAME                                      READY     STATUS      RESTARTS   AGE
default                 docker-registry-1-6xrxk                   1/1       Running     0          3m
default                 persistent-volume-setup-2qtmd             0/1       Completed   0          2m
default                 router-1-5ck5l                            1/1       Running     0          3m
devex                   configmapcontroller-1-f97j5               1/1       Running     0          1m
devex                   launcher-backend-2-2p4hd                  1/1       Running     0          1m
devex                   launcher-frontend-2-mswsf                 1/1       Running     0          1m
istio-system            elasticsearch-0                           1/1       Running     0          2m
istio-system            elasticsearch-1                           1/1       Running     0          1m
istio-system            grafana-6f4fd4986f-r872j                  1/1       Running     0          2m
istio-system            istio-ca-ddb878d84-l29bl                  1/1       Running     0          2m
istio-system            istio-ingress-76b5496c58-7s9xq            1/1       Running     0          2m
istio-system            istio-mixer-56f49dc667-6z9zz              3/3       Running     0          2m
istio-system            istio-mixer-validator-65c7fccc64-2j7qd    1/1       Running     0          2m
istio-system            istio-pilot-76dd785958-6ckmx              2/2       Running     0          2m
istio-system            istio-sidecar-injector-599d8c454c-q9ckl   1/1       Running     0          2m
istio-system            jaeger-agent-tj5hc                        1/1       Running     0          1m
istio-system            jaeger-collector-b86c6bf8d-dwdhm          1/1       Running     0          1m
istio-system            jaeger-query-6c8c85454-fgmmg              1/1       Running     0          1m
istio-system            openshift-ansible-istio-job-cphbd         0/1       Completed   0          2m
istio-system            prometheus-cf8456855-7fkmm                1/1       Running     0          2m
openshift-web-console   webconsole-7dfbffd44d-j9295               1/1       Running     0          3m

rincewind:origin kevin$ istiooc cluster down
rincewind:origin kevin$ istiooc cluster up --istio --launcher
rincewind:origin kevin$ istiooc login -u developer
Logged into "https://127.0.0.1:8443" as "developer" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
  * devex
    istio-system
    kube-public
    kube-system
    myproject
    openshift
    openshift-infra
    openshift-node
    openshift-web-console

Using project "devex".
rincewind:origin kevin$ oc get pods --all-namespaces
NAMESPACE               NAME                                      READY     STATUS      RESTARTS   AGE
default                 docker-registry-1-tds9r                   1/1       Running     0          2m
default                 persistent-volume-setup-kssns             0/1       Completed   0          2m
default                 router-1-mpgbt                            1/1       Running     0          2m
devex                   configmapcontroller-1-469z5               1/1       Running     0          1m
devex                   launcher-backend-2-xw5nj                  1/1       Running     0          1m
devex                   launcher-frontend-2-9kw8d                 1/1       Running     0          1m
istio-system            elasticsearch-0                           1/1       Running     0          1m
istio-system            elasticsearch-1                           1/1       Running     0          1m
istio-system            grafana-6f4fd4986f-swp8z                  1/1       Running     0          1m
istio-system            istio-ca-ddb878d84-vtbwd                  1/1       Running     0          2m
istio-system            istio-ingress-76b5496c58-tp84l            1/1       Running     0          2m
istio-system            istio-mixer-56f49dc667-8m7pp              3/3       Running     0          2m
istio-system            istio-mixer-validator-65c7fccc64-n2wmn    1/1       Running     0          2m
istio-system            istio-pilot-76dd785958-vv26l              2/2       Running     0          2m
istio-system            istio-sidecar-injector-599d8c454c-68rch   1/1       Running     0          1m
istio-system            jaeger-agent-7wmsw                        1/1       Running     0          1m
istio-system            jaeger-collector-b86c6bf8d-8rz4f          1/1       Running     0          1m
istio-system            jaeger-query-6c8c85454-dzndh              1/1       Running     0          1m
istio-system            openshift-ansible-istio-job-r8rkj         0/1       Completed   0          2m
istio-system            prometheus-cf8456855-5c27l                1/1       Running     0          1m
openshift-web-console   webconsole-7dfbffd44d-pb7cp               1/1       Running     0          2m</pre>

**Comment by knrc** [comment]
Question for you, did you wait until the installation job had finished before checking?

**Comment by cmoulliard** [comment]
> checking

not really but instead looking if the `devex` project was created. I will do a new test this morning and if some latency occurs again to recreate the launcher's project, then we will update the doc to warn the user.

**Comment by cmoulliard** [comment]
When we restart it, `devex` doesn't appear after 30s and at least 2min or more time are required to get the project

We will mention that withinin the doc

```
[vagrant@ibm-p8-kvm-03-guest-02 istiooc]$ oc get pods --all-namespaces
NAMESPACE               NAME                                      READY     STATUS      RESTARTS   AGE
default                 docker-registry-1-2gdp5                   1/1       Running     0          1m
default                 persistent-volume-setup-lmdbd             0/1       Completed   0          1m
default                 router-1-tkbxz                            1/1       Running     0          1m
istio-system            elasticsearch-0                           0/1       Running     0          2s
istio-system            grafana-6f4fd4986f-9ls9b                  1/1       Running     0          13s
istio-system            istio-ca-ddb878d84-4xggd                  1/1       Running     0          44s
istio-system            istio-ingress-76b5496c58-99kcx            1/1       Running     0          45s
istio-system            istio-mixer-56f49dc667-txb65              3/3       Running     0          47s
istio-system            istio-mixer-validator-65c7fccc64-tqgzk    1/1       Running     0          43s
istio-system            istio-pilot-76dd785958-bktpv              2/2       Running     0          45s
istio-system            istio-sidecar-injector-599d8c454c-mphwl   1/1       Running     0          29s
istio-system            openshift-ansible-istio-job-98fw5         1/1       Running     0          1m
istio-system            prometheus-cf8456855-69rnb                1/1       Running     0          10s
openshift-web-console   webconsole-7dfbffd44d-69dbr               1/1       Running     0          1m

[vagrant@ibm-p8-kvm-03-guest-02 istiooc]$ wait 4min

[vagrant@ibm-p8-kvm-03-guest-02 istiooc]$ oc get pods --all-namespaces
NAMESPACE               NAME                                      READY     STATUS             RESTARTS   AGE
default                 docker-registry-1-2gdp5                   1/1       Running            0          5m
default                 persistent-volume-setup-lmdbd             0/1       Completed          0          5m
default                 router-1-tkbxz                            1/1       Running            0          5m
devex                   configmapcontroller-1-4cf7c               1/1       Running            0          2m
devex                   launcher-backend-2-rfm22                  1/1       Running            0          1m
devex                   launcher-frontend-1-mbk6g                 1/1       Terminating        0          2m
devex                   launcher-frontend-2-9p59w                 1/1       Running            0          1m
istio-system            elasticsearch-0                           0/1       CrashLoopBackOff   5          4m
istio-system            grafana-6f4fd4986f-9ls9b                  1/1       Running            0          4m
istio-system            istio-ca-ddb878d84-4xggd                  1/1       Running            0          4m
istio-system            istio-ingress-76b5496c58-99kcx            1/1       Running            0          4m
istio-system            istio-mixer-56f49dc667-txb65              3/3       Running            0          4m
istio-system            istio-mixer-validator-65c7fccc64-tqgzk    1/1       Running            0          4m
istio-system            istio-pilot-76dd785958-bktpv              2/2       Running            0          4m
istio-system            istio-sidecar-injector-599d8c454c-mphwl   1/1       Running            0          4m
istio-system            jaeger-agent-8cj6k                        1/1       Running            0          2m
istio-system            jaeger-collector-b86c6bf8d-74npd          0/1       CrashLoopBackOff   4          2m
istio-system            jaeger-query-6c8c85454-jrbj7              0/1       CrashLoopBackOff   4          2m
istio-system            openshift-ansible-istio-job-98fw5         0/1       Completed          0          5m
istio-system            prometheus-cf8456855-69rnb                1/1       Running            0          4m
openshift-web-console   webconsole-7dfbffd44d-69dbr               1/1       Running            0          5m
```

**Comment by knrc** [comment]
The only possible connection to the installer I can think of would be that the delay could be related to your elasticsearch problems since the playbooks wait for elasticsearch to start before continuing with the rest of the installation, this is a prerequisite for jaeger to start cleanly.

Other than that it would be something related to your environment, perhaps resources?  I will likely be reverting the elasticsearch change to the pires version, you should try this again once that has been pushed out.

**Comment by cmoulliard** [comment]
Work better with more cpu, memory
