### ISSUE TITLE
Launcher parameters not used to configure Launcher ConfigMap

### ISSUE THREAD

**Issue by cmoulliard** [openshift-istio/origin#2]
Parameters passed to `oc cluster up --launcher ...` command aren't mapped to the Launcher ConfigMap

e.g

```
oc cluster up\
>   --public-hostname=192.168.99.50\
>   --istio\
>   --launcher\
>   --launcher-openshift-user=admin\
>   --launcher-openshift-password=admin\
>   --launcher-openshift-username=cmoulliard\
>   --launcher-openshift-token=MYTOKEN
```

Launcher ConfigMap created within the `devex` project doesn't contain them 

![screenshot 2018-04-18 12 32 14](https://user-images.githubusercontent.com/463790/38927034-c72b949c-4304-11e8-9bc3-0b34e638608d.png)

**Comment by knrc** [comment]
This looks to be an issue with the templating parameters in the inventory, I'll get this fixed

**Comment by knrc** [comment]
I've made a couple of changes and will push up a new release once I've completed your other request.

The templating is now fixed and I've also renamed the github parameters to launcher-github-username and launcher-github-token.

Once a new istiooc release is out you will be able to run the following

<pre>istiooc cluster up --istio --launcher --launcher-openshift-user=admin --launcher-openshift-password=admin --launcher-github-username=cmoulliard --launcher-github-token=MYTOKEN</pre>

**Comment by knrc** [comment]
<pre>rincewind:origin kevin$ istiooc get configmap launcher -o yaml
apiVersion: v1
data:
  launcher.backend.catalog.git.ref: master
  launcher.backend.catalog.git.repository: https://github.com/fabric8-launcher/launcher-booster-catalog.git
  launcher.backend.catalog.reindex.token: ""
  launcher.backend.environment: ""
  launcher.backend.url: /launch/api
  launcher.keycloak.realm: ""
  launcher.keycloak.url: ""
  launcher.missioncontrol.github.token: MYTOKEN
  launcher.missioncontrol.github.username: cmoulliard
  launcher.missioncontrol.openshift.api.url: https://172.30.0.1:443
  launcher.missioncontrol.openshift.console.url: https://127.0.0.1:8443
  launcher.missioncontrol.openshift.password: admin
  launcher.missioncontrol.openshift.username: admin
  launcher.missioncontrol.url: /launch
  launcher.tracker.segment.token: ""
kind: ConfigMap
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2018-04-18T21:13:03Z
  labels:
    app: fabric8-launcher
    template: launcher-header
  name: launcher
  namespace: devex
  resourceVersion: "2210"
  selfLink: /api/v1/namespaces/devex/configmaps/launcher
  uid: 47f4a38f-434d-11e8-924e-ca657eb5444b</pre>
