### ISSUE TITLE
Trace data not reported from service when istio-auth switch used

### ISSUE THREAD

**Issue by objectiser** [openshift-istio/origin#5]
When installing the wildfly swarm [distributed tracing booster](https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-istio-tracing) following the instructions:

```
istiooc cluster up --istio=true --istio-auth=true
```
this causes the Jaeger Java client (HTTP sender), using URL `http://jaeger-collector.istio-system:14268/api/traces` to get a `java.net.SocketException: Connection reset`.

When the `--istio-auth=true` switch is removed, the spans are reported successful.

The interesting thing is that the istio/envoy proxy is reporting spans to the Jaeger collector via the zipkin service without any problems.

##### Version
istiooc alpha8 (ocp 3.9.0)

##### Steps To Reproduce
1. Follow the instructions in the [distributed tracing booster](https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-istio-tracing), making sure the [HTTP URL ](https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-istio-tracing/blob/master/greeting-service/src/main/resources/project-defaults.yml#L8) is set to `'http://jaeger-collector.istio-system:14268/api/traces`
2. Open the browser on the example UI: http://istio-ingress-istio-system.127.0.0.1.nip.io/
3. Open the Jaeger UI - search for traces containing spans from the "greetings" service

**Comment by knrc** [comment]
Apologies, this issue was dealt with some time ago.  We now ensure the zipkin and jaeger-collector services are excluded from mTLS.
