### ISSUE TITLE
Missing some Kiali permissions

### ISSUE THREAD

**Issue by jotak** [openshift-istio/origin#8]
Some permissions are missing for Kiali to enable some functionalities related to OpenShift: in the Kiali deployment we've added a ClusterRoleBinding used to read openshift routes: see https://github.com/kiali/kiali/blob/master/deploy/openshift/kiali.yaml#L110-L115

Without it, we cannot get URLs to Grafana or Jaeger automatically (some extra config is needed).

I'm not sure where the kiali role / binding is defined in openshift-istio. I haven't found them, but if you can point it to me I'll be happy to contribute.

##### Version
oc istio-3.9-0.8.0-alpha2+cd746ec
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.9.0+a96a520-22
kubernetes v1.9.1+a0ce1bc657

##### Steps To Reproduce
1. Run cluster up
`istiooc cluster up  --istio --istio-kiali-version=0.3.1.Alpha --istio-kiali-username=admin --istio-kiali-password=admin`
2. Deploy a service mesh for instance bookinfo demo
3. In kiali, navigate to an istio-enabled sevice details, then click on "Metrics"

##### Current Result
An error shows that the Grafana URL cannot be detected. No link to Grafana at the bottom of the page.

##### Expected Result
No error, links to grafana at the bottom

**Comment by knrc** [comment]
On 18 June 2018 at 10:47, Joel Takvorian <notifications@github.com> wrote:

> Some permissions are missing for Kiali to enable some functionalities
> related to OpenShift: in the Kiali deployment we've added a
> ClusterRoleBinding used to read openshift routes: see
> https://github.com/kiali/kiali/blob/master/deploy/
> openshift/kiali.yaml#L110-L115
>
> Without it, we cannot get URLs to Grafana or Jaeger automatically (some
> extra config is needed).
>
> I'm not sure where the kiali role / binding is defined in openshift-istio.
> I haven't found them, but if you can point it to me I'll be happy to
> contribute.
>
I added the explicit route permission and that didn't appear to fix the
issue, there must be something else stopping this from working.  I'll
investigate further today.

   Kev

**Comment by knrc** [comment]
On 20 June 2018 at 08:39, Kevin Conner <kconner@redhat.com> wrote:

> I added the explicit route permission and that didn't appear to fix the
> issue, there must be something else stopping this from working.  I'll
> investigate further today.
>

I spoke too soon, I had a typo in the config file so a retesting.

   Kev

**Comment by knrc** [comment]
I've moved this over to the installer project
